### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by saranchockan** [ZeRoPoint1/memesh#2]
What is a meme?

**Comment by ZeRoPoint1** [comment]
Memetics is the study of information and culture based on an analogy with Darwinian evolution. Proponents describe memetics as an approach to evolutionary models of cultural information transfer. Critics regard memetics as a pseudoscience. Memetics describes how an idea can propogate successfully, but doesn't necessarily imply a concept is factual.

from https://en.wikipedia.org/wiki/Memetics

**Comment by saranchockan** [comment]
oh, I think this rep should be downright removed from GitHub. This rep is part of a larger hierarchal structure that promotes white supremacy/culture by spreading "memes" around the entire world portraying the white colonialist era. You talk about spreading "culture", but everything around the internet is absorbed by white culture and is essentially destroyed. You destroy the culture and dignity minorites such as African Americas, for example, by marking blackness as an ultimate downfall since most memes refer to a darker tone in a negative context. Please delete this rep !

**Comment by PotatoCurry** [comment]
no me

**Comment by PotatoCurry** [comment]
taking one for the team
